# Generated by Django 5.1.3 on 2024-11-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='fname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='origin',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
